# Generated by Django 3.2.25 on 2026-01-29 14:17

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields
import sugr_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('permission_codes', models.JSONField(blank=True, default=sugr_backend.models.default_permission_codes)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineData',
            fields=[
                ('medicine_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('medicine_data', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255, unique=True)),
                ('patient_personal_info', djongo.models.fields.JSONField()),
                ('patient_medicines', djongo.models.fields.JSONField()),
                ('patient_signed_hc', djongo.models.fields.JSONField()),
                ('patient_vitals', djongo.models.fields.JSONField(default=dict)),
                ('patient_notes', djongo.models.fields.JSONField(default=dict)),
                ('exit_info', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Kullanıcılar bu danışanı görebilir ve düzenleyebilir (sahip her zaman erişebilir).', related_name='accessible_patients', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('patient_id', models.CharField(max_length=255)),
                ('patient_firstname', models.CharField(max_length=255)),
                ('patient_lastname', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_category', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_by', models.CharField(max_length=255)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('file_data', models.TextField()),
                ('file_type', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
