# Generated by Django 3.2.25 on 2026-01-28 08:57

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sugr_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='exit_info',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
