# Generated by Django 3.2.25 on 2026-01-28 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sugr_backend', '0002_patientdata_exit_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('patient_id', models.CharField(max_length=255)),
                ('patient_firstname', models.CharField(max_length=255)),
                ('patient_lastname', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_category', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_by', models.CharField(max_length=255)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('file_data', models.TextField()),
                ('file_type', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
