# Generated by Django 3.2.25

from django.db import migrations, models


DEFAULT_CODES = [
    "view_dashboard", "view_patients", "view_drugs", "view_files",
    "edit_patient", "edit_patient_medicines", "edit_patient_notes",
    "add_patient", "add_file", "edit_file", "delete_file",
    "view_patient_detail",
]


def set_default_permissions(apps, schema_editor):
    User = apps.get_model('sugr_backend', 'User')
    for user in User.objects.all():
        if not user.permission_codes:
            user.permission_codes = DEFAULT_CODES
            user.save(update_fields=['permission_codes'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sugr_backend', '0003_filedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_codes',
            field=models.JSONField(
                blank=True,
                default=list,
            ),
        ),
        migrations.RunPython(set_default_permissions, noop),
    ]
