# Generated by Django 3.2.25 on 2026-01-29 12:56

from django.db import migrations, models
import sugr_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('sugr_backend', '0004_user_permission_codes'),
    ]

    operations = [
        # Only update migration state; no DB change (column type unchanged, default is Python-only).
        # Avoids ValueError from alter_field on JSONField in this environment.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='permission_codes',
                    field=models.JSONField(blank=True, default=sugr_backend.models.default_permission_codes),
                ),
            ],
            database_operations=[],
        ),
    ]
