# Generated by Django 3.2.25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugr_backend', '0005_alter_user_permission_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='allowed_users',
            field=models.ManyToManyField(
                blank=True,
                help_text='Kullanıcılar bu danışanı görebilir ve düzenleyebilir (sahip her zaman erişebilir).',
                related_name='accessible_patients',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
